### ISSUE TITLE
Recursive folder scan stops on too many folders

### ISSUE THREAD

**Issue by sirinsidiator** [ichaoX/ext-file#4]
When I try to scan a directory with many subdirectories the entries iterator randomly stops after some amount of folders and the whole script will just hang. No errors and no more console output when I log every file entry.

**Comment by ichaoX** [comment]
Are you using a Full or Lite type of Helper App? The current "helper-app-full-windows.zip" does have this problem, but the Lite version should not be affected.

What does the Helper App state in the Options page show?

Enable debugging of Content Script:
Open Options Page>Content Script>Configuration parameters
Add `DEBUG_ENABLED:true,` line and save.

Enable debugging for background page:
Open "about:debugging#/runtime/this-firefox">Extensions>File System Access>Inspect>Console
Run `util.debug=true`.

**Comment by sirinsidiator** [comment]
I am using the full release since it seemed more convenient to set up.
When it hangs and I click on recheck, both State and Version show "...".
Pressing stop and running the function again works until it stops again at a different random folder in the same parent directory.

The background script log shows 3 entries per directory and simply stops on a set like this:
```
18:32:37.045
Object { action: "fs.queryPermission", data: {…}, origin: "https://sir.insidi.at/" }
[main.js:26:10](moz-extension://1e766803-c97f-486c-87f1-c4f6f109aa4b/background/main.js)
18:32:37.045
Object { action: "fs.scandir", data: {…}, origin: "https://sir.insidi.at/" }
[main.js:26:10](moz-extension://1e766803-c97f-486c-87f1-c4f6f109aa4b/background/main.js)
18:32:37.046 request 
Object { action: "scandir", data: {…}, id: "1699637557046-328" }
```
The page console stops on two entries with the path to the parent folder followed by the words "entries" and "keys" respectively.

**Comment by ichaoX** [comment]
Try this version to see if it works?
[helper-app-full-windows.zip](https://github.com/ichaoX/ext-file/files/13321967/helper-app-full-windows.zip)

**Comment by sirinsidiator** [comment]
This version seems to work fine. Scanned past the folder where the other version stopped without a problem.

**Comment by sirinsidiator** [comment]
Looks like the new version is handing an incorrect date modified for files. It's in seconds instead of milliseconds.
